import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { NoiseInitiator, CipherState } from '../src/noise/crypto.js';
import { FrameAssembler, frameChunks, responseFrame, fields, bytes, integer } from '../src/noise/wire.js';

const vector = JSON.parse(readFileSync(new URL('./fixtures/noise.json', import.meta.url), 'utf8')) as Record<string, string>;
const from = (key: string) => Buffer.from(vector[key]!, 'hex');

test('Noise XX handshake and bidirectional encryption match the independent Python implementation', () => {
  const noise = new NoiseInitiator({ ephemeral: from('ephemeral'), static: from('static') });
  assert.deepEqual(noise.message1(), from('message1'));
  noise.receiveMessage2(from('message2'));
  const { message, send, receive } = noise.finish();
  assert.deepEqual(message, from('message3'));
  assert.deepEqual(send.encrypt(from('requestPlain')), from('requestCipher'));
  assert.deepEqual(receive.decrypt(from('responseCipher')), from('responsePlain'));
  assert.throws(() => noise.finish(), /state/);
});

test('tampered handshake poisons the handshake state', () => {
  const noise = new NoiseInitiator({ ephemeral: from('ephemeral'), static: from('static') });
  noise.message1();
  const message = from('message2');
  message[50] = message[50]! ^ 1;
  assert.throws(() => noise.receiveMessage2(message), /authentication/);
  assert.throws(() => noise.receiveMessage2(from('message2')), /state/);
});

test('replayed transport ciphertext is rejected and the cipher cannot be reused', () => {
  const key = Buffer.alloc(32, 4);
  const send = new CipherState(key), receive = new CipherState(key);
  const frame = send.encrypt(Buffer.from('hello'));
  assert.equal(receive.decrypt(frame).toString(), 'hello');
  assert.throws(() => receive.decrypt(frame), /authentication/);
  assert.throws(() => receive.decrypt(send.encrypt(Buffer.from('next'))), /unavailable/);
});

test('decodes a response generated by the Python reference', () => {
  const response = responseFrame(from('responsePlain'));
  assert.equal(response.streamId, 7);
  assert.equal(response.status, 200);
  assert.equal(response.body.toString(), '{"ok":true}');
  assert.equal(response.end, true);
});

test('multi-frame messages reassemble out of order', () => {
  const payload = Buffer.alloc(180000, 42);
  const chunks = frameChunks(payload, 0xffffffffffffffffn);
  const decoder = new FrameAssembler();
  assert.equal(decoder.decode(chunks[2]!), undefined);
  assert.equal(decoder.decode(chunks[0]!), undefined);
  assert.deepEqual(decoder.decode(chunks[1]!), payload);
});

test('duplicate chunks poison the decoder', () => {
  const chunks = frameChunks(Buffer.alloc(70000), 1n);
  const decoder = new FrameAssembler();
  decoder.decode(chunks[0]!);
  assert.throws(() => decoder.decode(chunks[0]!), /Inconsistent/);
  assert.throws(() => decoder.decode(chunks[1]!), /unavailable/);
});

test('malformed varints and truncated fields are rejected', () => {
  assert.throws(() => fields(Buffer.from([10, 255])), /varint/);
  assert.throws(() => fields(Buffer.from([10, 3, 1])), /Truncated/);
  assert.throws(() => fields(Buffer.from([0])), /field/);
  const decoder = new FrameAssembler();
  assert.throws(() => decoder.decode(Buffer.concat([integer(3, 300), bytes(4, 'x')])), /chunk/);
});
